### ISSUE TITLE
随笔🔖

### ISSUE THREAD

**Issue by Buzz2d0** [Buzz2d0/lboy-blog#21]
## mongodb 权限问题
> https://segmentfault.com/a/1190000015603831

总结：
- server 端 `—auth` 开身份验证。
- 创建 admin 用户
```bash
use admin
db.createUser( { user: "admin", pwd: "admin", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] } )
db.system.users.find() # 可以查看其他的 user 信息
```
不能用admin数据库中的用户登录其他数据库。
创建业务数据库的管理用户：
```bash
use aaa # database name
db.createUser( { user: "aaaadmin", pwd: "admin123", roles: [ { role: "readWrite", db:"aaa" } ] } )
```
登录时选择这个用户。

##  oh-my-zsh 终端提示设置
> https://www.jianshu.com/p/bf488bf22cba

总结：
- vim ~/.oh-my-zsh/themes/\`echo $ZSH_THEME\`.zsh-theme
- `PROMPT` 修改这个变量的值即可
完成：
![image](https://user-images.githubusercontent.com/26270009/77980118-158b4400-7339-11ea-81ea-4affd4162120.png)

##  Docker-compose Mysql 初始化多个数据库与多个用户
> https://www.jianshu.com/p/852bf683bcc0

前提：之前初始化数据库、数据库用户与密码 写在`envrionment`，表的的结构化 SQL 文件映射到`dockerl-entrypoint-initdb.d/dump.sql`。
```yml
services:
  mysql:
    image: mysql
    ...
    environment:
      MYSQL_DATABASE: XXX
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
    volumes:
      - ./mysql/dump.sql:/dockerl-entrypoint-initdb.d/dump.sql
```
创建其他的用户或者创建数据库时就会失败；需要将`envrionment` 中的环境变量移除，在将初始化的 SQL 文件目录映射到`/docker-entrypoint-initdb.d` 目录下即可，MySQL 启动完成后会判断 `docker-entrypoint-initdb.d`目录下是否有`sh/sql/sql.gz`文件，若有就执行初始化。

## Mac 端口已被监听
> https://www.lovesofttech.com/mac/macPort.html
> mac netstat 和 linux 下的 netstat 命令不一样的，如何查看全部的监听的端口

linux: `netstat -nltp` macos ` -  macos: `netstat -anvf inet`

查看看占用端口进程等相关信息  `lsof -i :[port]`

## Github Search
> https://github.com/search/advanced
## Google Search
> https://mp.weixin.qq.com/s/1qH_zmzJWNxHgs3PWKZ1TA
